### ISSUE TITLE
How do I add ChromaHUD to my mod folder?

### ISSUE THREAD

**Issue by Apfelmus1337** [AstrqlDev/ChromaHUD#1]
Hey!

How do I added ChromaHUD to my mod folder?

**Comment by AstrqlDev** [comment]
Hey,

How to use?

Press the windows key, and r at the same time

Type %appdata%

Click on the .minecraft folder

Click on the mods folder

Place the mod in the mods folder

Start up your minecraft

Once minecraft is launched press the right control (ctrl) key, and itll open up a GUI. Enjoy.

**Comment by Apfelmus1337** [comment]
Ok and why are you hosting a fake repo of the decompiled source of my mod?
